CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260908030507_EsquemaInicial') THEN
    CREATE TABLE "Pedidos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "NumeroPedido" character varying(50) NOT NULL,
        "Cliente" character varying(150) NOT NULL,
        "Fecha" timestamp with time zone NOT NULL,
        "Total" numeric(10,2) NOT NULL,
        "Estado" character varying(50) NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "FechaActualizacion" timestamp with time zone,
        "Eliminado" boolean NOT NULL,
        "FechaEliminacion" timestamp with time zone,
        CONSTRAINT "PK_Pedidos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260908030507_EsquemaInicial') THEN
    CREATE TABLE "Usuarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Email" character varying(256) NOT NULL,
        "PasswordHash" character varying(200) NOT NULL,
        "Nombre" character varying(150) NOT NULL,
        "Rol" character varying(20) NOT NULL,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "FechaActualizacion" timestamp with time zone,
        "Eliminado" boolean NOT NULL,
        "FechaEliminacion" timestamp with time zone,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260908030507_EsquemaInicial') THEN
    CREATE UNIQUE INDEX "IX_Pedidos_NumeroPedido_Activos" ON "Pedidos" ("NumeroPedido") WHERE "Eliminado" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260908030507_EsquemaInicial') THEN
    CREATE UNIQUE INDEX "IX_Usuarios_Email_Activos" ON "Usuarios" ("Email") WHERE "Eliminado" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260908030507_EsquemaInicial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260908030507_EsquemaInicial', '9.0.19');
    END IF;
END $EF$;
COMMIT;

